name: Build ViewTheWord MacOS App

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  build:
    name: Build and upload DMG
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Archive
        run: |
          bash build.sh
      - name: Install create-dmg
        run: |
          brew install create-dmg
      - name: Create DMG
        run: |
          create-dmg --eula LICENSE --no-internet-enable --skip-jenkins --icon "ViewTheWord.app" 20 300 --app-drop-link 100 300 --window-pos 400 100 --window-size 640 400 ViewTheWord.dmg build/ViewTheWord.app
      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: ViewTheWord
          path: ViewTheWord.dmg
          retention-days: 400
